version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    build:
      context: ./docker
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
      DB_FILTER: ${DB_FILTER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      LIMIT_TIME_CPU: ${LIMIT_TIME_CPU}
      LIMIT_TIME_REAL: ${LIMIT_TIME_REAL}
      WORKERS: ${WORKERS}
      TRAKKA_API_JWT_SECRET: ${TRAKKA_API_JWT_SECRET}
      TRAKKA_API_TOKEN_AUDIENCE: ${TRAKKA_API_TOKEN_AUDIENCE}
      TRAKKA_API_TOKEN_ISSUER: ${TRAKKA_API_TOKEN_ISSUER}
    volumes:
      - ./addons:/mnt/extra-addons
      - ./docker/odoo.conf:/etc/odoo/odoo.conf
      - filestore:/var/lib/odoo
    command: ["/entrypoint.sh"]
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:8069/web/login || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10

volumes:
  db-data:
  filestore:
